name: My Skipper Lifestyle
favicon: null
layout_spectrum: 0.26706
typography_spectrum: 0.90014
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#9ca1a5'
    - '#ffd9a5'
    - '#423836'
    - '#da7c62'
  brandStrength: 0.25
  lightness: 0.06806535739451647
  saturation: 0.14513194002211094
  rhythmicContrast: 0.25
purpose: []
